name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  check:
    name: Prepare release...
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci

  maybe-release:
    name: release
    runs-on: ubuntu-latest
    needs: [check]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}